const consts = {
    ADD_POST: "ADD_POST",
    REMOVE_POST: "REMOVE_POST",
    UPDATE_POST: "UPDATE_POST",
    POST_REVISION: "POST_REVISION",
    ADD_UP_VOTE: "ADD_UP_VOTE",
    ADD_DOWN_VOTE: "ADD_DOWN_VOTE",
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
    CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS"
};

export default consts